In [1]:
# import useful libraries

import numpy as np
import itertools
from collections import Counter
from utils import load_puzzle_input, test_code

In [2]:
# load puzzle input
    
puzzle_input = load_puzzle_input('input.txt')

print(puzzle_input[:3])

['011112220220323233332231343014141131140112421211413355234334024414242133303312210313023000021220102', '221002103112233201234202003421134043024153515443332415451142151141323114321301434333033210022221022', '201200003311133331441214403131041312551423522332422531524232533513033233434420203421023110323221022']


### Part 1

In [3]:
# code for preparing and testing examples for part 1

example_dict_part_1 = {
    tuple(load_puzzle_input('example_1.txt')): 21
}

In [4]:
def parse_puzzle_input(puzzle_input):
    return np.array([[int(character) for character in line] for line in puzzle_input])

In [ ]:
def check_if_visible(row_idx, col_idx, tree_grid):
    if row_idx in {0, tree_grid.shape[0]} or col_idx in {0, tree_grid.shape[1]}:
        return False
    else:
        tree_height = tree_grid[row_idx, col_idx]
        if tree_height >= max(tree_grid[row_idx,:]) and tree_height >= max(tree_grid[:,col_idx]):
            return True
    return False

In [7]:
def part_1_solution(puzzle_input):

    return parse_puzzle_input(puzzle_input)

In [11]:
test_array = np.array(
    [[3, 0, 3, 7, 3],
 [2, 5, 5, 1, 2],
 [6, 5, 3, 3, 2],
 [3, 3, 5, 4, 9],
[3, 5, 3, 9, 0]
]

)

In [16]:
test_array[2,2]

3

In [8]:
# test part 1 solution

test_code(part_1_solution, example_dict_part_1)

[[3 0 3 7 3]
 [2 5 5 1 2]
 [6 5 3 3 2]
 [3 3 5 4 9]
 [3 5 3 9 0]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### Part 2

In [ ]:
# code for preparing and testing examples for part 2

example_dict_part_2 = {
    tuple(load_puzzle_input('example_1.txt')): "example_output"
}

In [ ]:
# test part 2 solution

# test_code(func, example_dict_part_2)